Netflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/urls.py
#url #view #template

from django.urls import path, reverse_lazy
from .views import Homefilmes, Homepage, Detalhesfilme, Pesquisafilme, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view


app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('Pesquisafilme/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name= 'login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name= 'logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
# Create your models here.

LISTA_CATEGORIAS =(
    ("ANALISES", "Amálises"),
    ("PROGRAMACAO","Programação"),
    ("APRESENTACAO","Apresentação"),
    ("OUTROS","Outros"),
)

#Criar o Filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=20, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo

#Criar os episodios
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo


#Criar o usuário
class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme, Usuario
from .forms import CriarContaForm
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
#def homepage(request):
    #return render(request, "homepage.html")

class Homepage(TemplateView):
    template_name = "homepage.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('filme:homefilmes')
        else:
            return super().get(request, *args, **kwargs)

class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme
    # object_list

class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme

    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs)

class Pesquisafilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self). get_context_data(**kwargs)
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:5]
        context["filmes_relacionados"] = filmes_relacionados
        return context

class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('filme:login')

# url - view -html
#def homefilmes(request):
    #context = {}
    #lista_filmes = Filme.objects.all()
    #context['lista_filmes'] = lista_filmes
    #return render(request, "homefilmes.html", context)

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/westminster3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-slate-50 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group border-2">
                    <legend class=" border-bottom mb-2">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="text-black bg-sky-50 shadow-lg shadow-blue-500/50  py-2 px-3 rounded-full hover:bg-slate-300 border-double border-4 border-sky-700 transition-colors  " type="submit">Criar Conta</button>
            </form>

        </div>
    </header>

    <footer class="px-4 py-1">
        <ul class="flex justify-between items-center">

            <li>&copy; 2022</li>
            <li> Feito com Python (Django)</li>
            <li>WestminsterFilms</li>
        </ul>
    </footer>
{% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}
WestminsterFilms
{% endblock %}


{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ object.titulo }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white text-justify my-4">
                    {{ object.descricao }}
                </p>
                <div class="flex my-0 ">
                    <a href="{{ object.episodios.first.video }}">
                        <button class="flex items bg-red-600 py-2 px-5 rounded-md hover:bg-red-500" style='color:white;'>
                            <ion-icon name="play" class="text-2xl hover:bg-sky-700"></ion-icon>
                            <span class="ml-2 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify py-1'>
            <div class="p-4 w-10/12 relative" >
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episódios
                    </h2>
                    {% for episodio in object.episodios.all %}
                        <h3 class='text-lg'>
                            <a href="{{ episodio.video }}">
                                <p>Episódio {{ forloop.counter }}: {{ episodio.titulo }}</p>
                            </a>
                        </h3>
                    {% endfor %}
                </div>

            </div>
        </section>

        <section class='bg-primary_black flex justify py-1'>
            <div class="p-4 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for filme in filmes_relacionados %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>


    </main>

{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/westminster3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl ">{{ user.username }}</h2>
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                  {{ form|crispy }}
                </fieldset>
                <button class="text-black bg-sky-50 shadow-lg shadow-blue-500/50  py-2 px-3 rounded-full hover:bg-slate-300 transition-colors" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-4 py-1 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2022</li>
            <li> Feito com Python (Django)</li>
            <li>WestminsterFilms</li>
        </ul>
    </footer>

{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
WestminsterFilms
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;

    .item {
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }

    }

    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;

      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }

    }

  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>

{% endblock %}


{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ filme_destaque.titulo }}
                </h2>
                <p class="w-11/12 md:w-5/12 font-medium text-white justify my-4">
                    {{ filme_destaque.descricao }}
                </p>
                <div class="flex my-4 justify">
                    <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                        <button class="flex items-center bg-white py-2 px-5 hover:bg-red-300 transition-colors rounded-md " style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium " >
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>


        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                  <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_emalta %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                        <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if lista_filmes_emalta|length > 4 %}
                      <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                          {% for filme in lista_filmes_emalta %}
                          {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>


            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                  <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_emalta %}
                      {% if forloop.counter < 5 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                        <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                    {% if lista_filmes_emalta|length > 4 %}
                      <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                          {% for filme in lista_filmes_emalta %}
                          {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                              </a>
                          </div>
                          {% endif %}
                          {% endfor %}
                        <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                      </section>
                    {% endif %}
                </div>


            </div>
        </section>

    </main>

{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
WestminsterFilms
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-transparent bg-cover bg-center bg  bg-opacity- bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/westminster3.jpg' %}');">
    </header>
{% endblock %}

<div class="py-10">
    <h2>Novo</h2>
    {{ lista_filmes_recentes }}
</div>

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Fazer Login
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/westminster3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
            {{ form|crispy }}
                </fieldset>
                <button class="text-black bg-sky-50 shadow-lg shadow-blue-500/50  py-2 px-3 rounded-full hover:bg-slate-300 border-double border-4 border-sky-700 transition-colors" type="submit">Fazer Login</button>
            </form>
            <small class ="py-3 px-3 ">
                Não tem uma conta ainda? <p><a href="{% url 'filme:criarconta' %}">Clique aqui para criar uma conta</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-4 py-1 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2022</li>
            <li> Feito com Python (Django)</li>
            <li>WestminsterFilms</li>
        </ul>
    </footer>
{% endblock %}

filme/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-transparent bg-cover bg-center bg  bg-opacity- bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/westminster3.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">Você saiu da sua conta</h2>
            <div class="flex flex-nowrap justify-center space-x-5 p-5">
            <a href="{% url 'filme:login' %}"><button class="bg-red-600 py-2 px-3 rounded-full hover:bg-red-500 ">Fazer Login</button></a>
            <a href="{% url 'filme:criarconta' %}"><button class="bg-red-600 py-2 px-3 rounded-full hover:bg-red-500">Criar uma Conta</button></a>
            </div>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2022</li>
            <li> Feito com Python (Django)</li>
            <li>WestminsterFilms</li>
        </ul>
    </footer>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head%}
    {% endblock %}
</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

<script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            if(scrollY>100){
                if(scrollY>window.innerHeight){
                nav.classList.add('invisible')
            }else{
                nav.classList.add('bg-black-500')
                nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })

</script>

</body>
</html>

templates/navbar.html
{% load static %}

<nav class="flex text-gray-100 justify-between items-center py-3 px-4 fixed w-full z-50 text-white">
        <div class="w-5/12">
            <a href='/'>
            <img src="{% static 'images/novologo1.png' %}" alt="logo" class="w-5/12 md:w-2/12">
            </a>
        </div>

        <div class="w-6/12 flex flex-nowrap justify-end">
              {% if user.is_authenticated %}
              <div class="mr-2">
                  <form method="get" action="#">
                      <input class="py-2 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" type="text" placeholder="Pesquisar...">
                      <input type="submit" value="">
                  </form>
              </div>
              {% endif %}
              <div class="mr-2">
                  {% if user.is_authenticated %}
                  <a href="{% url 'filme:logout' %}" class="">
                    <button class='text-black bg-sky-50 shadow-lg shadow-blue-500/50  py-2 px-3 rounded-md hover:bg-slate-300 transition-colors'>
                        Sair
                    </button>
                  </a>
                  {% else %}
              </div>
              <div class="mr-2">
                  <a href="{% url 'filme:login' %}" class="">
                    <button class='text-black bg-sky-50 shadow-lg shadow-blue-500/50 flex items py-2 px-3 rounded-md hover:bg-slate-300 transition-colors'>
                        Entrar
                    </button>
                  </a>
                  {% endif %}
              </div>
              {% if user.is_authenticated %}
              <div class="mr-2">
                <a href="{% url 'filme:editarperfil' user.pk %}" class="">
                    <button class='text-black bg-sky-50 shadow-lg shadow-blue-500/50  py-2 px-3 rounded-md hover:bg-slate-300 transition-colors '>
                        Editar Perfil
                    </button>
                </a>
              </div>
              {% endif %}
    </div>

</nav>